/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FaceAnalysisService } from "../faceAnalysis.service";
import { FaceAnalysisCreateInput } from "./FaceAnalysisCreateInput";
import { FaceAnalysis } from "./FaceAnalysis";
import { FaceAnalysisFindManyArgs } from "./FaceAnalysisFindManyArgs";
import { FaceAnalysisWhereUniqueInput } from "./FaceAnalysisWhereUniqueInput";
import { FaceAnalysisUpdateInput } from "./FaceAnalysisUpdateInput";
import { FaceDetectionEventFindManyArgs } from "../../faceDetectionEvent/base/FaceDetectionEventFindManyArgs";
import { FaceDetectionEvent } from "../../faceDetectionEvent/base/FaceDetectionEvent";
import { FaceDetectionEventWhereUniqueInput } from "../../faceDetectionEvent/base/FaceDetectionEventWhereUniqueInput";

export class FaceAnalysisControllerBase {
  constructor(protected readonly service: FaceAnalysisService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FaceAnalysis })
  async createFaceAnalysis(
    @common.Body() data: FaceAnalysisCreateInput
  ): Promise<FaceAnalysis> {
    return await this.service.createFaceAnalysis({
      data: data,
      select: {
        age: true,
        createdAt: true,
        emotions: true,
        eyeColor: true,
        faceShape: true,
        gender: true,
        id: true,
        imageUrl: true,
        skinTone: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FaceAnalysis] })
  @ApiNestedQuery(FaceAnalysisFindManyArgs)
  async faceAnalyses(@common.Req() request: Request): Promise<FaceAnalysis[]> {
    const args = plainToClass(FaceAnalysisFindManyArgs, request.query);
    return this.service.faceAnalyses({
      ...args,
      select: {
        age: true,
        createdAt: true,
        emotions: true,
        eyeColor: true,
        faceShape: true,
        gender: true,
        id: true,
        imageUrl: true,
        skinTone: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FaceAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async faceAnalysis(
    @common.Param() params: FaceAnalysisWhereUniqueInput
  ): Promise<FaceAnalysis | null> {
    const result = await this.service.faceAnalysis({
      where: params,
      select: {
        age: true,
        createdAt: true,
        emotions: true,
        eyeColor: true,
        faceShape: true,
        gender: true,
        id: true,
        imageUrl: true,
        skinTone: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FaceAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFaceAnalysis(
    @common.Param() params: FaceAnalysisWhereUniqueInput,
    @common.Body() data: FaceAnalysisUpdateInput
  ): Promise<FaceAnalysis | null> {
    try {
      return await this.service.updateFaceAnalysis({
        where: params,
        data: data,
        select: {
          age: true,
          createdAt: true,
          emotions: true,
          eyeColor: true,
          faceShape: true,
          gender: true,
          id: true,
          imageUrl: true,
          skinTone: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FaceAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFaceAnalysis(
    @common.Param() params: FaceAnalysisWhereUniqueInput
  ): Promise<FaceAnalysis | null> {
    try {
      return await this.service.deleteFaceAnalysis({
        where: params,
        select: {
          age: true,
          createdAt: true,
          emotions: true,
          eyeColor: true,
          faceShape: true,
          gender: true,
          id: true,
          imageUrl: true,
          skinTone: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/faceDetectionEvents")
  @ApiNestedQuery(FaceDetectionEventFindManyArgs)
  async findFaceDetectionEvents(
    @common.Req() request: Request,
    @common.Param() params: FaceAnalysisWhereUniqueInput
  ): Promise<FaceDetectionEvent[]> {
    const query = plainToClass(FaceDetectionEventFindManyArgs, request.query);
    const results = await this.service.findFaceDetectionEvents(params.id, {
      ...query,
      select: {
        camera: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        faceAnalysis: {
          select: {
            id: true,
          },
        },

        id: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/faceDetectionEvents")
  async connectFaceDetectionEvents(
    @common.Param() params: FaceAnalysisWhereUniqueInput,
    @common.Body() body: FaceDetectionEventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      faceDetectionEvents: {
        connect: body,
      },
    };
    await this.service.updateFaceAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/faceDetectionEvents")
  async updateFaceDetectionEvents(
    @common.Param() params: FaceAnalysisWhereUniqueInput,
    @common.Body() body: FaceDetectionEventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      faceDetectionEvents: {
        set: body,
      },
    };
    await this.service.updateFaceAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/faceDetectionEvents")
  async disconnectFaceDetectionEvents(
    @common.Param() params: FaceAnalysisWhereUniqueInput,
    @common.Body() body: FaceDetectionEventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      faceDetectionEvents: {
        disconnect: body,
      },
    };
    await this.service.updateFaceAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }
}
