/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsEnum,
  ValidateNested,
  IsDate,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumFaceAnalysisEyeColor } from "./EnumFaceAnalysisEyeColor";
import { FaceDetectionEventUpdateManyWithoutFaceAnalysesInput } from "./FaceDetectionEventUpdateManyWithoutFaceAnalysesInput";
import { Type } from "class-transformer";
import { EnumFaceAnalysisFaceShape } from "./EnumFaceAnalysisFaceShape";
import { EnumFaceAnalysisGender } from "./EnumFaceAnalysisGender";
import { EnumFaceAnalysisSkinTone } from "./EnumFaceAnalysisSkinTone";

@InputType()
class FaceAnalysisUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  age?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  emotions?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumFaceAnalysisEyeColor,
  })
  @IsEnum(EnumFaceAnalysisEyeColor)
  @IsOptional()
  @Field(() => EnumFaceAnalysisEyeColor, {
    nullable: true,
  })
  eyeColor?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => FaceDetectionEventUpdateManyWithoutFaceAnalysesInput,
  })
  @ValidateNested()
  @Type(() => FaceDetectionEventUpdateManyWithoutFaceAnalysesInput)
  @IsOptional()
  @Field(() => FaceDetectionEventUpdateManyWithoutFaceAnalysesInput, {
    nullable: true,
  })
  faceDetectionEvents?: FaceDetectionEventUpdateManyWithoutFaceAnalysesInput;

  @ApiProperty({
    required: false,
    enum: EnumFaceAnalysisFaceShape,
  })
  @IsEnum(EnumFaceAnalysisFaceShape)
  @IsOptional()
  @Field(() => EnumFaceAnalysisFaceShape, {
    nullable: true,
  })
  faceShape?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumFaceAnalysisGender,
  })
  @IsEnum(EnumFaceAnalysisGender)
  @IsOptional()
  @Field(() => EnumFaceAnalysisGender, {
    nullable: true,
  })
  gender?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  imageUrl?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumFaceAnalysisSkinTone,
  })
  @IsEnum(EnumFaceAnalysisSkinTone)
  @IsOptional()
  @Field(() => EnumFaceAnalysisSkinTone, {
    nullable: true,
  })
  skinTone?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  timestamp?: Date | null;
}

export { FaceAnalysisUpdateInput as FaceAnalysisUpdateInput };
